const ActionTypes = {
    FETCH_MOVIE_DETAIL_SUCCESS: "FETCH_MOVIE_DETAIL_SUCCESS",
    FETCH_MOVIE_DETAIL_ERROR: "FETCH_MOVIE_DETAIL_ERROR",
    FETCH_MOVIE_DETAIL_LOADING: "FETCH_MOVIE_DETAIL_LOADING",
    FETCH_MOVIES_LIST_SUCCESS: "FETCH_MOVIES_LIST_SUCCESS",
    FETCH_MOVIES_LIST_ERROR: "FETCH_MOVIES_LIST_ERROR",
    FETCH_MOVIES_LIST_LOADING: "FETCH_MOVIES_LIST_LOADING",
    IS_VIDEO_PLAYER_MODULE_OPEN: "IS_VIDEO_PLAYER_MODULE_OPEN",
    IS_VIDEO_PLAYER_MODULE_CLOSE: "IS_VIDEO_PLAYER_MODULE_CLOSE"
};

export default ActionTypes;
  